force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Hours_Assigned_Resource__c.field-meta.xml
<CustomField>
    <fullName>Hours_Assigned_Resource__c</fullName>
    <label>Hours Assigned Resource</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskAssignationService.cls
public with sharing class TaskAssignationService {
    
    public static Boolean registrar_tareas(String strJSON){
        List<Task__c> tareas_ListaJSON = (List<Task__c>)JSON.deserialize(strJSON, List<Task__c>.class);
        insert tareas_ListaJSON;
        return true;
    }
    
    public class Proyecto_Recursos_Tareas{
        @AuraEnabled
        public List<Project_Resource__c> proyecto_recursos_lista;
        @AuraEnabled
        public Project__c proyecto;
        @AuraEnabled
        public List<Task__c> tareas;
        
        public proyecto_recursos_tareas(List<Project_Resource__c> proyecto_recursos_lista,
                                        Project__c proyecto, List<Task__c> tareas){
        	this.proyecto_recursos_lista = proyecto_recursos_lista;
            this.proyecto = proyecto;
            this.tareas = tareas;
        }
    }
    
    public Proyecto_Recursos_Tareas obtener_Proyecto_Recursos_Tarea(Id proId){
        
        Project__c pro = [SELECT Name, Date_Start__c, Date_End__c, 
                          		 Status__c
                          FROM Project__c
                          WHERE Id = :proId];
        
        List<Project_Resource__c> proyecto_recursos_lista = [SELECT Date_Start__c, Date_End__c, 
                                                              		Hours_Assigned_Resource__c,
                                                             		Resource__c, Resource__r.Name
                                                             FROM Project_Resource__c
                                                             WHERE Project__c = :proId];
        
        List<Task__c> tareas = [SELECT Date_Start__c, Date_End__c,
                                	   Project_Resource__c, Project_Resource__r.Project__c,
                                	   Project_Resource__r.Resource__c
                                FROM Task__c
                                WHERE Project_Resource__r.Project__c = :proId];
        
        
        Proyecto_Recursos_Tareas instanciada = new Proyecto_Recursos_Tareas(proyecto_recursos_lista, pro, tareas);
        
        return instanciada;
    }
}