force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Project_Resource__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Request_Date_End__c.field-meta.xml
<CustomField>
    <fullName>Request_Date_End__c</fullName>
    <label>Request Date End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Request_Date_Start__c.field-meta.xml
<CustomField>
    <fullName>Request_Date_Start__c</fullName>
    <label>Request Date Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Request_Description__c.field-meta.xml
<CustomField>
    <fullName>Request_Description__c</fullName>
    <label>Request Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submited For Approval</fullName>
                <default>true</default>
                <label>Submited For Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <formula>Project_Resource__r.Resource__r.FirstName+&apos; &apos;+Project_Resource__r.Resource__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Squad_Lead__c.field-meta.xml
<CustomField>
    <fullName>Squad_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Squad Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectsList.cls
public with sharing class ProjectsList {
    
    @AuraEnabled(cacheable=True)
    public static Map<String, List<Project__c>> getProjectsByUser(String userId) {
        Map<String, List<Project__c>> projectMap = new Map<String, List<Project__c>>();
        
        List<Project__c> projectManagerProjects = [SELECT Id, Name, Status__c, Date_Start__c, Date_End__c, Squad_Lead__c, 
                                                          Squad_Lead__r.Name
                                                   FROM Project__c
                                                   WHERE Project_Manager__c = :userId
                                                   ORDER BY Date_Start__c DESC];
        
        projectMap.put('projectManagerProjects', projectManagerProjects);
        
        List<Project__c> squadLeadProjects = [SELECT Id, Name, Status__c, Date_Start__c, Date_End__c, Project_Manager__c,
                                                     Squad_Lead__c
                                              FROM Project__c
                                              WHERE Squad_Lead__c = :userId
                                              ORDER BY Date_Start__c DESC];
        
        projectMap.put('squadLeadProjects', squadLeadProjects);                                       
        
        return projectMap;  
    }
    
    
    @AuraEnabled(cacheable=True)
    public static Map<Id, List<Task__c>> getTaskByUser(String userId) {
        Map<Id, List<Task__c>> taskMap = new Map<Id, List<Task__c>>();
        
        List<Task__c> tareas_Lista = [SELECT Name, Project_Resource__r.Project__c, 
                                      		 Project_Resource__r.Project__r.Name
                                      FROM Task__c
                                      WHERE Project_Resource__c = :userId
                                      ORDER BY Date_Start__c DESC];
        
        if(!tareas_Lista.isEmpty()){
        	for(Task__c t: tareas_Lista){
                if(!taskMap.containsKey(t.Project_Resource__r.Project__c)){
                    taskMap.put(t.Project_Resource__r.Project__c, new List<Task__c>{t});
                }else{
                    taskMap.get(t.Project_Resource__r.Project__c).add(t);            
                }
        	}    
        }
                        
        return taskMap;     
    }
    
    @AuraEnabled(cacheable=True)
    public static List<Application__c> getVacationByUser(String userId) {
        
        List<Application__c> vacaciones_Lista = [SELECT Request_Description__c, Request_Status__c, Request_Date_End__c, Request_Date_Start__c
                                      		 	 FROM Application__c
                                      		 	 WHERE Project_Resource__r.Resource__c = :userId
                                      		 	 ORDER BY Request_Date_Start__c DESC];        
        return vacaciones_Lista;     
    }
}